
# .github/workflows/main.yml
name: HDL Simulation CI

# いつ走らせるか
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - testpys/**
      - .github/workflows/**
  pull_request:
    branches:
      - main
    paths:
      - src/*
      - testpys/**
      - .github/workflows/**

jobs:
  simulate:
    name: Run Cocotb Tests
    runs-on: ubuntu-latest
    container: ubuntu:24.04

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: install deps in container
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            python3 python3-venv python3-pip help2man verilator 

      - name: Create and activate venv
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip cocotb


      - name: Run simulation
        # repo 直下で Makefile の sim ターゲットを実行
        run: |
          source venv/bin/activate
          make sim SIM=verilator